import Head from "next/head";
import Footer from "../components/footer";
import Link from "next/link";
import ThemeSwitcher from "../components/themeSwitcher";
import { Text, Divider, VStack, Container, Button } from "@chakra-ui/react";
import { HomeTitle } from "../styles/Global";

export default function Home() {
  return (
    <Container maxW="md" height="100vh" centerContent justifyContent="center">
      <Head>
        <title>Lista - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ThemeSwitcher />

      <VStack>
        <HomeTitle>To Do List</HomeTitle>
        <Divider />
        <Button colorScheme="green" variant="ghost">
          <Link href="/list" fontSize={"lg"}>
            <a textDecoration="none">Iniciar</a>
          </Link>
        </Button>
      </VStack>

      <Footer />
    </Container>
  );
}

// Tutorial - https://www.youtube.com/watch?v=9P8mASSREYM&list=PLC3y8-rFHvwgC9mj0qv972IO5DmD-H0ZH
